#include "RustCodeGenerator.h"
#include "Console.h"
#include "Contracts.h"
#include "GeneratorPlugin.h"
#include <cctype>
#include <fstream>
#include <functional>

RustCodeGenerator::RustCodeGenerator(
    const runtime::AST* ast, const runtime::SemanticAnalyzer* analyzer, const runtime::Array<runtime::String>& namespaces, const runtime::String& classPrefix) :
    runtime::ICodeGenerator(ast, analyzer, namespaces, classPrefix)
{
    BuildInheritanceMap();
}

bool RustCodeGenerator::Generate(const runtime::String& outputPath)
{
    if (nullptr == ast_)
    {
        ReportError("Cannot generate code from null runtime::AST");
        return false;
    }

    Console::ReportStatus("Phase 2 (Code Generation) started...");

    // Generate code into output stream
    GenerateFileHeader(outputPath);

    // Generate all declarations
    const auto& declarations = ast_->GetDeclarations();
    for (const auto& decl : declarations)
    {
        if (runtime::Declaration::Kind::ENUM == decl->GetKind())
        {
            GenerateEnum(decl->AsEnum());
        }
        else if (runtime::Declaration::Kind::CLASS == decl->GetKind())
        {
            GenerateClass(decl->AsClass());
        }
    }

    GenerateFileFooter();

    // Write to file
    std::ofstream outFile(outputPath.GetValue());
    if (outFile.is_open() == false)
    {
        ReportError("Failed to open output file: " + outputPath);
        return false;
    }

    outFile << output_.str();
    outFile.close();

    Console::ReportStatus("Rust code generated successfully: " + outputPath);
    return HasErrors() == false;
}

runtime::String RustCodeGenerator::GetFileExtension() const
{
    return ".rs";
}

runtime::String RustCodeGenerator::GetLanguageName() const
{
    return "Rust";
}

runtime::String RustCodeGenerator::MapPrimitiveType(runtime::PrimitiveType type) const
{
    switch (type)
    {
        case runtime::PrimitiveType::STRING:
            return "String";
        case runtime::PrimitiveType::INT:
            return "i64";
        case runtime::PrimitiveType::REAL:
            return "f64";
        case runtime::PrimitiveType::BOOL:
            return "bool";
        case runtime::PrimitiveType::TIMESTAMP:
            return "chrono::DateTime<chrono::Utc>";
        case runtime::PrimitiveType::TIMESPAN:
            return "chrono::Duration";
        case runtime::PrimitiveType::DATE:
            return "chrono::NaiveDate";
        case runtime::PrimitiveType::GUID:
            return "uuid::Uuid";
        default:
            return "Unknown";
    }
}

runtime::String RustCodeGenerator::MapType(const runtime::TypeSpec* typeSpec, const runtime::CardinalityModifier* cardinality) const
{
    RequireReturn(nullptr != typeSpec, runtime::String{"()"});

    runtime::String baseType;

    if (typeSpec->IsPrimitive())
    {
        const runtime::PrimitiveTypeSpec* primType = dynamic_cast<const runtime::PrimitiveTypeSpec*>(typeSpec);
        baseType                                   = MapPrimitiveType(primType->GetType());
    }
    else
    {
        const runtime::UserDefinedTypeSpec* userType = dynamic_cast<const runtime::UserDefinedTypeSpec*>(typeSpec);
        baseType                                     = ApplyClassPrefix(userType->GetTypeName());
    }

    // Handle optional
    if (nullptr != cardinality && cardinality->IsOptional())
    {
        baseType = "Option<" + baseType + ">";
    }

    // Handle arrays
    if (nullptr != cardinality && cardinality->IsArray())
    {
        baseType = "Vec<" + baseType + ">";
    }

    return baseType;
}

void RustCodeGenerator::GenerateFileHeader(const runtime::String& filename)
{
    // Extract just the filename from path
    const size_t          lastSlash    = filename.GetValue().find_last_of("/\\");
    const runtime::String justFilename = (lastSlash != std::string::npos) ? runtime::String(filename.GetValue().substr(lastSlash + 1)) : filename;

    output_ << "// Generated by Model Compiler\n";
    output_ << "// Target: Rust 2024\n";
    output_ << "// Output: " << justFilename << "\n";
    output_ << "\n";

    // Generate use statements
    output_ << "#![allow(dead_code)]\n";
    output_ << "\n";
    output_ << "use chrono::{DateTime, Duration, NaiveDate, Utc};\n";
    output_ << "use serde::{Deserialize, Serialize};\n";
    output_ << "use uuid::Uuid;\n";
    output_ << "\n";

    // Generate ValidationError enum
    output_ << "/// Validation error for invariant violations\n";
    output_ << "#[derive(Debug, Clone, PartialEq, Eq)]\n";
    output_ << "pub enum ValidationError {\n";
    output_ << "    /// runtime::Invariant constraint was violated\n";
    output_ << "    InvariantViolation(&'static str),\n";
    output_ << "    /// Attempted to access/modify field on wrong enum variant\n";
    output_ << "    WrongVariant,\n";
    output_ << "}\n";
    output_ << "\n";

    // Generate FabricMetadata
    output_ << "/// Universal metadata fields present in all model types\n";
    output_ << "#[derive(Debug, Clone, Serialize, Deserialize)]\n";
    output_ << "pub struct FabricMetadata {\n";
    output_ << "    /// Unique identifier for the type itself (same for all instances of a type)\n";
    output_ << "    pub type_id: Uuid,\n";
    output_ << "    /// Unique identifier for this instance\n";
    output_ << "    pub id: Uuid,\n";
    output_ << "    /// Cardinality of the type instance\n";
    output_ << "    pub cardinality: i64,\n";
    output_ << "    /// When this instance was created\n";
    output_ << "    pub creation_date: DateTime<Utc>,\n";
    output_ << "    /// When this instance was last modified\n";
    output_ << "    pub modification_date: DateTime<Utc>,\n";
    output_ << "    /// User comment/notes\n";
    output_ << "    pub comment: String,\n";
    output_ << "}\n";
    output_ << "\n";

    // Open module namespace if specified
    if (namespaces_.GetCount() > 0)
    {
        for (const auto& ns : namespaces_)
        {
            output_ << "pub mod " << ns << " {\n";
            output_ << "    use super::*;\n";
            output_ << "\n";
        }
    }
}

void RustCodeGenerator::GenerateFileFooter()
{
    // Close module namespaces
    if (namespaces_.GetCount() > 0)
    {
        output_ << "\n";
        for (size_t i = 0; i < namespaces_.GetCount(); ++i)
        {
            output_ << "}\n";
        }
    }
}

void RustCodeGenerator::GenerateEnum(const runtime::EnumDeclaration* enumDecl)
{
    const runtime::String enumName = ApplyClassPrefix(enumDecl->GetName());

    WriteIndent(namespaces_.GetCount());
    output_ << "/// Enumeration: " << enumName << "\n";
    WriteIndent(namespaces_.GetCount());
    output_ << "#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\n";
    WriteIndent(namespaces_.GetCount());
    output_ << "pub enum " << enumName << " {\n";

    for (const auto& value : enumDecl->GetValues())
    {
        WriteIndent(namespaces_.GetCount() + 1);
        output_ << value << ",\n";
    }

    WriteIndent(namespaces_.GetCount());
    output_ << "}\n";
    output_ << "\n";
}

void RustCodeGenerator::GenerateClass(const runtime::ClassDeclaration* classDecl)
{
    const runtime::String className = classDecl->GetName();

    // If this class is a base class (has derived classes), generate enum
    if (IsBaseClass(className) == true)
    {
        GenerateInheritedEnum(classDecl);
        return;
    }

    // If this class inherits from another, it will be generated as part of the base enum
    if (classDecl->GetBaseType().IsEmpty() == false)
    {
        return; // Skip - handled by base class enum generation
    }

    // Otherwise, generate as struct
    GenerateStruct(classDecl);
    GenerateImpl(classDecl);
}

void RustCodeGenerator::GenerateInheritedEnum(const runtime::ClassDeclaration* baseClass)
{
    const runtime::String baseName = ApplyClassPrefix(baseClass->GetName());

    // Generate base struct for shared fields
    GenerateBaseStruct(baseClass);

    // Generate enum with variants
    WriteIndent(namespaces_.GetCount());
    output_ << "/// Enum for " << baseName << " hierarchy\n";
    WriteIndent(namespaces_.GetCount());
    output_ << "#[derive(Debug, Clone, Serialize, Deserialize)]\n";
    WriteIndent(namespaces_.GetCount());
    output_ << "pub enum " << baseName << " {\n";

    // Generate variant for each derived class
    const runtime::Array<const runtime::ClassDeclaration*>* derived = derivedClasses_.GetValuePtr(baseClass->GetName());
    if (nullptr == derived)
    {
        return;
    }

    for (const auto* derivedClass : *derived)
    {
        runtime::String variantName = ApplyClassPrefix(derivedClass->GetName());
        // Remove base name prefix if present (AudioAsset -> Audio if base is Asset)
        if (variantName.GetLength() > baseName.GetLength() && variantName.GetValue().compare(0, baseName.GetLength(), baseName.GetValue()) == 0)
        {
            variantName = runtime::String(variantName.GetValue().substr(baseName.GetLength()));
        }

        WriteIndent(namespaces_.GetCount() + 1);
        output_ << variantName << " {\n";
        WriteIndent(namespaces_.GetCount() + 2);
        output_ << "base: " << baseName << "Fields,\n";

        // Add derived class fields
        for (const auto& field : derivedClass->GetFields())
        {
            if (field->IsComputed() == true || field->IsAlias() == true)
            {
                continue; // Skip computed and alias fields
            }

            WriteIndent(namespaces_.GetCount() + 2);
            output_ << ToSnakeCase(field->GetName()) << ": " << MapType(field->GetType(), field->GetCardinalityModifier()) << ",\n";
        }

        WriteIndent(namespaces_.GetCount() + 1);
        output_ << "},\n";
    }

    WriteIndent(namespaces_.GetCount());
    output_ << "}\n";
    output_ << "\n";

    // Generate impl block
    GenerateInheritedEnumImpl(baseClass);
}

void RustCodeGenerator::GenerateBaseStruct(const runtime::ClassDeclaration* baseClass)
{
    const runtime::String baseName = ApplyClassPrefix(baseClass->GetName());

    WriteIndent(namespaces_.GetCount());
    output_ << "/// Base fields for " << baseName << "\n";
    WriteIndent(namespaces_.GetCount());
    output_ << "#[derive(Debug, Clone, Serialize, Deserialize)]\n";
    WriteIndent(namespaces_.GetCount());
    output_ << "pub struct " << baseName << "Fields {\n";

    WriteIndent(namespaces_.GetCount() + 1);
    output_ << "pub metadata: FabricMetadata,\n";

    for (const auto& field : baseClass->GetFields())
    {
        if (field->IsComputed() == true || field->IsAlias() == true)
        {
            continue; // Skip computed and alias fields
        }

        WriteIndent(namespaces_.GetCount() + 1);
        output_ << "pub " << ToSnakeCase(field->GetName()) << ": " << MapType(field->GetType(), field->GetCardinalityModifier()) << ",\n";
    }

    WriteIndent(namespaces_.GetCount());
    output_ << "}\n";
    output_ << "\n";
}

void RustCodeGenerator::GenerateStruct(const runtime::ClassDeclaration* classDecl)
{
    const runtime::String className = ApplyClassPrefix(classDecl->GetName());

    WriteIndent(namespaces_.GetCount());
    output_ << "/// Class: " << className << "\n";
    WriteIndent(namespaces_.GetCount());
    output_ << "#[derive(Debug, Clone, Serialize, Deserialize)]\n";
    WriteIndent(namespaces_.GetCount());
    output_ << "pub struct " << className << " {\n";

    // Universal metadata
    WriteIndent(namespaces_.GetCount() + 1);
    output_ << "pub metadata: FabricMetadata,\n";

    // Fields
    for (const auto& field : classDecl->GetFields())
    {
        if (field->IsComputed() == true || field->IsAlias() == true)
        {
            continue; // Skip computed and alias fields (they become methods)
        }

        WriteIndent(namespaces_.GetCount() + 1);
        output_ << "pub " << ToSnakeCase(field->GetName()) << ": " << MapType(field->GetType(), field->GetCardinalityModifier()) << ",\n";
    }

    WriteIndent(namespaces_.GetCount());
    output_ << "}\n";
    output_ << "\n";
}

void RustCodeGenerator::GenerateImpl(const runtime::ClassDeclaration* classDecl)
{
    const runtime::String className = ApplyClassPrefix(classDecl->GetName());

    WriteIndent(namespaces_.GetCount());
    output_ << "impl " << className << " {\n";

    // Generate getters
    for (const auto& field : classDecl->GetFields())
    {
        if (field->IsAlias() == true)
        {
            continue; // Skip aliases for now
        }

        if (field->IsComputed() == true)
        {
            GenerateComputedGetter(field.get(), classDecl, false);
        }
        else
        {
            GenerateGetter(field.get(), className, false);
        }
    }

    // Generate setters for fields with invariants
    for (const auto& field : classDecl->GetFields())
    {
        if (field->IsComputed() == false && field->IsAlias() == false)
        {
            const auto invariants = GetInvariantsForField(field->GetName(), classDecl);
            if (invariants.GetCount() > 0)
            {
                GenerateSetter(field.get(), classDecl, false);
            }
        }
    }

    WriteIndent(namespaces_.GetCount());
    output_ << "}\n";
    output_ << "\n";
}

void RustCodeGenerator::GenerateInheritedEnumImpl(const runtime::ClassDeclaration* baseClass)
{
    const runtime::String                                   baseName = ApplyClassPrefix(baseClass->GetName());
    const runtime::Array<const runtime::ClassDeclaration*>* derived  = derivedClasses_.GetValuePtr(baseClass->GetName());
    if (nullptr == derived)
    {
        return;
    }

    WriteIndent(namespaces_.GetCount());
    output_ << "impl " << baseName << " {\n";

    // Generate getters for base fields
    for (const auto& field : baseClass->GetFields())
    {
        if (field->IsAlias() == true)
        {
            continue;
        }

        if (field->IsComputed() == true)
        {
            GenerateComputedGetter(field.get(), baseClass, true);
        }
        else
        {
            GenerateGetter(field.get(), baseName, true);
        }
    }

    // Generate getters and setters for derived fields
    for (const auto* derivedClass : *derived)
    {
        runtime::String variantName = ApplyClassPrefix(derivedClass->GetName());
        if (variantName.GetLength() > baseName.GetLength() && variantName.GetValue().compare(0, baseName.GetLength(), baseName.GetValue()) == 0)
        {
            variantName = runtime::String(variantName.GetValue().substr(baseName.GetLength()));
        }

        for (const auto& field : derivedClass->GetFields())
        {
            if (field->IsAlias() == true)
            {
                continue;
            }

            if (field->IsComputed() == true)
            {
                // Computed getter for variant-specific field
                WriteIndent(namespaces_.GetCount() + 1);
                output_ << "/// Get computed field: " << field->GetName() << " (variant: " << variantName << ")\n";
                WriteIndent(namespaces_.GetCount() + 1);
                output_ << "pub fn " << ToSnakeCase(field->GetName()) << "(&self) -> Option<";
                const runtime::PrimitiveTypeSpec* primType = dynamic_cast<const runtime::PrimitiveTypeSpec*>(field->GetType());
                output_ << MapPrimitiveType(primType->GetType()) << "> {\n";
                WriteIndent(namespaces_.GetCount() + 2);
                output_ << "if let " << baseName << "::" << variantName << " { ";

                // List all fields needed for the expression
                runtime::Array<runtime::String> fieldRefs;
                for (const auto& f : derivedClass->GetFields())
                {
                    if (f->IsComputed() == false && f->IsAlias() == false)
                    {
                        fieldRefs.AddValue(ToSnakeCase(f->GetName()));
                    }
                }
                for (const auto& f : baseClass->GetFields())
                {
                    if (f->IsComputed() == false && f->IsAlias() == false)
                    {
                        fieldRefs.AddValue(ToSnakeCase(f->GetName()));
                    }
                }

                output_ << "base, ";
                for (size_t i = 0; i < fieldRefs.GetCount(); ++i)
                {
                    output_ << fieldRefs.GetValueAt(i);
                    if (i + 1 < fieldRefs.GetCount())
                    {
                        output_ << ", ";
                    }
                }
                output_ << ", .. } = self {\n";
                WriteIndent(namespaces_.GetCount() + 3);
                output_ << "Some(" << ExpressionToRust(field->GetInitializer(), "") << ")\n";
                WriteIndent(namespaces_.GetCount() + 2);
                output_ << "} else {\n";
                WriteIndent(namespaces_.GetCount() + 3);
                output_ << "None\n";
                WriteIndent(namespaces_.GetCount() + 2);
                output_ << "}\n";
                WriteIndent(namespaces_.GetCount() + 1);
                output_ << "}\n";
                output_ << "\n";
            }
            else
            {
                // Regular getter
                WriteIndent(namespaces_.GetCount() + 1);
                output_ << "/// Get field: " << field->GetName() << " (variant: " << variantName << ")\n";
                WriteIndent(namespaces_.GetCount() + 1);
                const runtime::String rustType = MapType(field->GetType(), field->GetCardinalityModifier());
                const bool needsRef = (rustType.GetValue().find("String") != std::string::npos || rustType.GetValue().find("Vec<") != std::string::npos);
                output_ << "pub fn " << ToSnakeCase(field->GetName()) << "(&self) -> Option<";
                if (needsRef == true)
                {
                    output_ << "&" << rustType;
                }
                else
                {
                    output_ << rustType;
                }
                output_ << "> {\n";
                WriteIndent(namespaces_.GetCount() + 2);
                output_ << "if let " << baseName << "::" << variantName << " { " << ToSnakeCase(field->GetName()) << ", .. } = self {\n";
                WriteIndent(namespaces_.GetCount() + 3);
                if (needsRef == true)
                {
                    output_ << "Some(" << ToSnakeCase(field->GetName()) << ")\n";
                }
                else
                {
                    output_ << "Some(*" << ToSnakeCase(field->GetName()) << ")\n";
                }
                WriteIndent(namespaces_.GetCount() + 2);
                output_ << "} else {\n";
                WriteIndent(namespaces_.GetCount() + 3);
                output_ << "None\n";
                WriteIndent(namespaces_.GetCount() + 2);
                output_ << "}\n";
                WriteIndent(namespaces_.GetCount() + 1);
                output_ << "}\n";
                output_ << "\n";
            }

            // Setter if field has invariants
            const auto invariants = GetInvariantsForField(field->GetName(), derivedClass);
            if (invariants.GetCount() > 0 && field->IsComputed() == false)
            {
                GenerateSetter(field.get(), derivedClass, true);
            }
        }
    }

    WriteIndent(namespaces_.GetCount());
    output_ << "}\n";
    output_ << "\n";
}

void RustCodeGenerator::GenerateGetter(const runtime::Field* field, const runtime::String& className, bool isInEnum)
{
    Require(nullptr != field);

    const runtime::String fieldName = ToSnakeCase(field->GetName());
    const runtime::String rustType  = MapType(field->GetType(), field->GetCardinalityModifier());
    const bool            needsRef  = (rustType.GetValue().find("String") != std::string::npos || rustType.GetValue().find("Vec<") != std::string::npos);

    WriteIndent(namespaces_.GetCount() + 1);
    output_ << "/// Get field: " << field->GetName() << "\n";
    WriteIndent(namespaces_.GetCount() + 1);
    output_ << "pub fn " << fieldName << "(&self) -> ";

    if (true == isInEnum)
    {
        if (needsRef == true)
        {
            output_ << "&" << rustType;
        }
        else
        {
            output_ << rustType;
        }
        output_ << " {\n";
        WriteIndent(namespaces_.GetCount() + 2);
        output_ << "match self {\n";

        // Generate match arms for all variants
        const runtime::Array<const runtime::ClassDeclaration*>* derived = derivedClasses_.GetValuePtr(className);
        if (nullptr == derived)
        {
            return;
        }

        for (size_t i = 0; i < derived->GetCount(); ++i)
        {
            runtime::String variantName = ApplyClassPrefix(derived->GetValueAt(i)->GetName());
            if (variantName.GetLength() > className.GetLength() && variantName.GetValue().compare(0, className.GetLength(), className.GetValue()) == 0)
            {
                variantName = runtime::String(variantName.GetValue().substr(className.GetLength()));
            }

            WriteIndent(namespaces_.GetCount() + 3);
            output_ << className << "::" << variantName << " { base, .. }";
            if (i < derived->GetCount() - 1)
            {
                output_ << " |\n";
            }
            else
            {
                output_ << " => ";
                if (needsRef == true)
                {
                    output_ << "&base." << fieldName << ",\n";
                }
                else
                {
                    output_ << "base." << fieldName << ",\n";
                }
            }
        }

        WriteIndent(namespaces_.GetCount() + 2);
        output_ << "}\n";
    }
    else
    {
        if (needsRef == true)
        {
            output_ << "&" << rustType << " {\n";
            WriteIndent(namespaces_.GetCount() + 2);
            output_ << "&self." << fieldName << "\n";
        }
        else
        {
            output_ << rustType << " {\n";
            WriteIndent(namespaces_.GetCount() + 2);
            output_ << "self." << fieldName << "\n";
        }
    }

    WriteIndent(namespaces_.GetCount() + 1);
    output_ << "}\n";
    output_ << "\n";
}

void RustCodeGenerator::GenerateSetter(const runtime::Field* field, const runtime::ClassDeclaration* classDecl, bool isInEnum)
{
    Require(nullptr != field);
    Require(nullptr != classDecl);

    const runtime::String fieldName  = ToSnakeCase(field->GetName());
    const runtime::String className  = ApplyClassPrefix(classDecl->GetName());
    const runtime::String rustType   = MapType(field->GetType(), field->GetCardinalityModifier());
    const auto            invariants = GetInvariantsForField(field->GetName(), classDecl);

    WriteIndent(namespaces_.GetCount() + 1);
    output_ << "/// Set field: " << field->GetName() << " (validates invariants)\n";
    WriteIndent(namespaces_.GetCount() + 1);
    output_ << "pub fn set_" << fieldName << "(&mut self, value: " << rustType << ") -> Result<(), ValidationError> {\n";

    if (true == isInEnum)
    {
        // For enum variants, need to match and update
        const runtime::String baseName    = classDecl->GetBaseType();
        runtime::String       variantName = className;
        if (variantName.GetLength() > baseName.GetLength() && variantName.GetValue().compare(0, baseName.GetLength(), baseName.GetValue()) == 0)
        {
            variantName = runtime::String(variantName.GetValue().substr(baseName.GetLength()));
        }

        WriteIndent(namespaces_.GetCount() + 2);
        output_ << "if let " << ApplyClassPrefix(baseName) << "::" << variantName << " { " << fieldName << ", .. } = self {\n";
        WriteIndent(namespaces_.GetCount() + 3);
        output_ << "let old_value = " << fieldName << ".clone();\n";
        WriteIndent(namespaces_.GetCount() + 3);
        output_ << "*" << fieldName << " = value;\n";

        // Check invariants
        for (const auto* inv : invariants)
        {
            WriteIndent(namespaces_.GetCount() + 3);
            output_ << "if !(" << ExpressionToRust(inv->GetExpression(), "*") << ") {\n";
            WriteIndent(namespaces_.GetCount() + 4);
            output_ << "*" << fieldName << " = old_value;\n";
            WriteIndent(namespaces_.GetCount() + 4);
            output_ << "return Err(ValidationError::InvariantViolation(\"" << inv->GetName() << "\"));\n";
            WriteIndent(namespaces_.GetCount() + 3);
            output_ << "}\n";
        }

        WriteIndent(namespaces_.GetCount() + 3);
        output_ << "Ok(())\n";
        WriteIndent(namespaces_.GetCount() + 2);
        output_ << "} else {\n";
        WriteIndent(namespaces_.GetCount() + 3);
        output_ << "Err(ValidationError::WrongVariant)\n";
        WriteIndent(namespaces_.GetCount() + 2);
        output_ << "}\n";
    }
    else
    {
        WriteIndent(namespaces_.GetCount() + 2);
        output_ << "let old_value = self." << fieldName << ".clone();\n";
        WriteIndent(namespaces_.GetCount() + 2);
        output_ << "self." << fieldName << " = value;\n";

        // Check invariants
        for (const auto* inv : invariants)
        {
            WriteIndent(namespaces_.GetCount() + 2);
            output_ << "if !(";
            output_ << ExpressionToRust(inv->GetExpression()) << ") {\n";
            WriteIndent(namespaces_.GetCount() + 3);
            output_ << "self." << fieldName << " = old_value;\n";
            WriteIndent(namespaces_.GetCount() + 3);
            output_ << "return Err(ValidationError::InvariantViolation(\"" << inv->GetName() << "\"));\n";
            WriteIndent(namespaces_.GetCount() + 2);
            output_ << "}\n";
        }

        WriteIndent(namespaces_.GetCount() + 2);
        output_ << "Ok(())\n";
    }

    WriteIndent(namespaces_.GetCount() + 1);
    output_ << "}\n";
    output_ << "\n";
}

void RustCodeGenerator::GenerateComputedGetter(const runtime::Field* field, const runtime::ClassDeclaration* classDecl, bool isInEnum)
{
    Require(nullptr != field);
    Require(nullptr != classDecl);

    const runtime::String             fieldName = ToSnakeCase(field->GetName());
    const runtime::PrimitiveTypeSpec* primType  = dynamic_cast<const runtime::PrimitiveTypeSpec*>(field->GetType());
    const runtime::String             rustType  = MapPrimitiveType(primType->GetType());

    WriteIndent(namespaces_.GetCount() + 1);
    output_ << "/// Computed field: " << field->GetName() << "\n";
    WriteIndent(namespaces_.GetCount() + 1);
    output_ << "pub fn " << fieldName << "(&self) -> " << rustType << " {\n";

    if (true == isInEnum)
    {
        WriteIndent(namespaces_.GetCount() + 2);
        output_ << "match self {\n";

        const runtime::String                                   className = ApplyClassPrefix(classDecl->GetName());
        const runtime::Array<const runtime::ClassDeclaration*>* derived   = derivedClasses_.GetValuePtr(classDecl->GetName());
        if (nullptr == derived)
        {
            return;
        }

        for (size_t i = 0; i < derived->GetCount(); ++i)
        {
            runtime::String variantName = ApplyClassPrefix(derived->GetValueAt(i)->GetName());
            if (variantName.GetLength() > className.GetLength() && variantName.GetValue().compare(0, className.GetLength(), className.GetValue()) == 0)
            {
                variantName = runtime::String(variantName.GetValue().substr(className.GetLength()));
            }

            WriteIndent(namespaces_.GetCount() + 3);
            output_ << className << "::" << variantName << " { base, .. }";
            if (i < derived->GetCount() - 1)
            {
                output_ << " |\n";
            }
            else
            {
                output_ << " => " << ExpressionToRust(field->GetInitializer(), "base.") << ",\n";
            }
        }

        WriteIndent(namespaces_.GetCount() + 2);
        output_ << "}\n";
    }
    else
    {
        WriteIndent(namespaces_.GetCount() + 2);
        output_ << ExpressionToRust(field->GetInitializer()) << "\n";
    }

    WriteIndent(namespaces_.GetCount() + 1);
    output_ << "}\n";
    output_ << "\n";
}

runtime::Array<const runtime::Invariant*>
    RustCodeGenerator::GetInvariantsForField(const runtime::String& fieldName, const runtime::ClassDeclaration* classDecl) const
{
    RequireReturn(nullptr != classDecl, runtime::Array<const runtime::Invariant*>{});
    RequireReturn(fieldName.IsEmpty() == false, runtime::Array<const runtime::Invariant*>{});

    runtime::Array<const runtime::Invariant*> result;

    for (const auto& inv : classDecl->GetInvariants())
    {
        // Simple check: does the expression reference this field?
        // This is a simplified version - full implementation would traverse the expression tree
        std::function<bool(const runtime::Expression*)> referencesField = [&](const runtime::Expression* expr) -> bool {
            if (nullptr == expr)
            {
                return false;
            }

            if (const runtime::FieldReference* fieldRef = dynamic_cast<const runtime::FieldReference*>(expr))
            {
                return fieldRef->GetFieldName() == fieldName;
            }

            if (const runtime::BinaryExpression* binExpr = dynamic_cast<const runtime::BinaryExpression*>(expr))
            {
                return referencesField(binExpr->GetLeft()) || referencesField(binExpr->GetRight());
            }

            if (const runtime::UnaryExpression* unExpr = dynamic_cast<const runtime::UnaryExpression*>(expr))
            {
                return referencesField(unExpr->GetOperand());
            }

            return false;
        };

        if (referencesField(inv->GetExpression()) == true)
        {
            result.AddValue(inv.get());
        }
    }

    return result;
}

runtime::String RustCodeGenerator::ExpressionToRust(const runtime::Expression* expr, const runtime::String& prefix) const
{
    if (nullptr == expr)
    {
        return "()";
    }

    // Literal expression
    if (const runtime::LiteralExpression* litExpr = dynamic_cast<const runtime::LiteralExpression*>(expr))
    {
        const runtime::Expression::Type type = litExpr->GetResultType();
        switch (type)
        {
            case runtime::Expression::Type::INT:
                return std::to_string(litExpr->GetIntValue());
            case runtime::Expression::Type::REAL:
            case runtime::Expression::Type::TIMESTAMP:
            case runtime::Expression::Type::TIMESPAN:
                return std::to_string(litExpr->GetRealValue());
            case runtime::Expression::Type::BOOL:
                return litExpr->GetBoolValue() == true ? "true" : "false";
            case runtime::Expression::Type::STRING:
            case runtime::Expression::Type::GUID:
                return "\"" + litExpr->GetStringValue() + "\"";
            default:
                return "/* unknown literal */";
        }
    }

    // runtime::Field reference
    if (const runtime::FieldReference* fieldRef = dynamic_cast<const runtime::FieldReference*>(expr))
    {
        return prefix + ToSnakeCase(fieldRef->GetFieldName());
    }

    // Member access
    if (const runtime::MemberAccessExpression* memberExpr = dynamic_cast<const runtime::MemberAccessExpression*>(expr))
    {
        return ExpressionToRust(memberExpr->GetObject(), prefix) + "." + ToSnakeCase(memberExpr->GetMemberName());
    }

    // Parenthesized expression
    if (const runtime::ParenthesizedExpression* parenExpr = dynamic_cast<const runtime::ParenthesizedExpression*>(expr))
    {
        return "(" + ExpressionToRust(parenExpr->GetExpression(), prefix) + ")";
    }

    // Binary expression
    if (const runtime::BinaryExpression* binExpr = dynamic_cast<const runtime::BinaryExpression*>(expr))
    {
        const runtime::String left  = ExpressionToRust(binExpr->GetLeft(), prefix);
        const runtime::String right = ExpressionToRust(binExpr->GetRight(), prefix);
        runtime::String       op;

        switch (binExpr->GetOperator())
        {
            case runtime::BinaryExpression::Op::ADD:
                op = " + ";
                break;
            case runtime::BinaryExpression::Op::SUB:
                op = " - ";
                break;
            case runtime::BinaryExpression::Op::MUL:
                op = " * ";
                break;
            case runtime::BinaryExpression::Op::DIV:
                op = " / ";
                break;
            case runtime::BinaryExpression::Op::MOD:
                op = " % ";
                break;
            case runtime::BinaryExpression::Op::LT:
                op = " < ";
                break;
            case runtime::BinaryExpression::Op::GT:
                op = " > ";
                break;
            case runtime::BinaryExpression::Op::LE:
                op = " <= ";
                break;
            case runtime::BinaryExpression::Op::GE:
                op = " >= ";
                break;
            case runtime::BinaryExpression::Op::EQ:
                op = " == ";
                break;
            case runtime::BinaryExpression::Op::NE:
                op = " != ";
                break;
            case runtime::BinaryExpression::Op::AND:
                op = " && ";
                break;
            case runtime::BinaryExpression::Op::OR:
                op = " || ";
                break;
        }

        return "(" + left + op + right + ")";
    }

    // Unary expression
    if (const runtime::UnaryExpression* unExpr = dynamic_cast<const runtime::UnaryExpression*>(expr))
    {
        const runtime::String operand = ExpressionToRust(unExpr->GetOperand(), prefix);

        switch (unExpr->GetOperator())
        {
            case runtime::UnaryExpression::Op::NEG:
                return "-" + operand;
            case runtime::UnaryExpression::Op::NOT:
                return "!" + operand;
        }
    }

    return "/* unknown expression */";
}

runtime::String RustCodeGenerator::ApplyClassPrefix(const runtime::String& name) const
{
    if (classPrefix_.IsEmpty() == true)
    {
        return name;
    }
    return classPrefix_ + name;
}

runtime::String RustCodeGenerator::ToSnakeCase(const runtime::String& name) const
{
    std::string        result;
    bool               lastWasUpper = false;
    const std::string& nameValue    = name.GetValue();

    for (size_t i = 0; i < nameValue.size(); ++i)
    {
        const char c = nameValue[i];

        if (std::isupper(c) != 0)
        {
            if (i > 0 && false == lastWasUpper)
            {
                result += '_';
            }
            result       += static_cast<char>(std::tolower(c));
            lastWasUpper  = true;
        }
        else
        {
            result       += c;
            lastWasUpper  = false;
        }
    }

    return runtime::String(result);
}

void RustCodeGenerator::BuildInheritanceMap()
{
    // Build map of base class -> derived classes
    for (const auto& decl : ast_->GetDeclarations())
    {
        if (runtime::Declaration::Kind::CLASS == decl->GetKind())
        {
            const runtime::ClassDeclaration* classDecl = decl->AsClass();
            if (nullptr != classDecl && classDecl->GetBaseType().IsEmpty() == false)
            {
                const runtime::String baseClass = classDecl->GetBaseType();
                derivedClasses_.GetOrCreate(baseClass).AddValue(classDecl);
                baseClasses_.insert(baseClass);
            }
        }
    }
}

bool RustCodeGenerator::IsBaseClass(const runtime::String& className) const
{
    return baseClasses_.find(className) != baseClasses_.end();
}

void RustCodeGenerator::WriteIndent(int level)
{
    for (int i = 0; i < level; ++i)
    {
        output_ << "    ";
    }
}

namespace {
runtime::Array<runtime::String> CopyNamespaces(const GeneratorCreateContext* context)
{
    runtime::Array<runtime::String> namespaces;

    if (nullptr == context || nullptr == context->namespaces)
    {
        return namespaces;
    };
    for (size_t i = 0; i < context->namespaceCount; ++i)
    {
        if (nullptr != context->namespaces[i])
        {
            namespaces.AddValue(runtime::String(context->namespaces[i]));
        }
    }

    return namespaces;
}
} // namespace

extern "C" PLUGIN_EXPORT runtime::CapabilitiesDictionary* GetCapabilities()
{
    auto* capabilities = new runtime::CapabilitiesDictionary();
    capabilities->SetValue("ApiVersion", std::to_string(GENERATOR_PLUGIN_API_VERSION).c_str());
    capabilities->SetValue("Language", "Rust");
    capabilities->SetValue("FileExtension", ".rs");
    capabilities->SetValue("Experimental", "true");
    return capabilities;
}

extern "C" PLUGIN_EXPORT void DestroyCapabilities(runtime::CapabilitiesDictionary* capabilities)
{
    delete capabilities;
}

extern "C" PLUGIN_EXPORT runtime::ICodeGenerator* CreateGenerator(const GeneratorCreateContext* context)
{
    if (nullptr == context || nullptr == context->ast || nullptr == context->analyzer)
    {
        return nullptr;
    }

    const runtime::Array<runtime::String> namespaces  = CopyNamespaces(context);
    const runtime::String                 classPrefix = (nullptr != context->classPrefix) ? context->classPrefix : "";

    return new RustCodeGenerator(context->ast, context->analyzer, namespaces, classPrefix);
}

extern "C" PLUGIN_EXPORT void DestroyGenerator(runtime::ICodeGenerator* generator)
{
    delete generator;
}
