// Generated by BBFM Model Compiler
// Target: Rust 2024
// Output: test_computed_simple.rs

#![allow(dead_code)]

use chrono::{DateTime, Duration, NaiveDate, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Validation error for invariant violations
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ValidationError {
    /// Invariant constraint was violated
    InvariantViolation(&'static str),
    /// Attempted to access/modify field on wrong enum variant
    WrongVariant,
}

/// Universal metadata fields present in all BBFM types
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FabricMetadata {
    /// Unique identifier for the type itself (same for all instances of a type)
    pub type_id: Uuid,
    /// Unique identifier for this instance
    pub id: Uuid,
    /// Cardinality of the type instance
    pub cardinality: i64,
    /// When this instance was created
    pub creation_date: DateTime<Utc>,
    /// When this instance was last modified
    pub modification_date: DateTime<Utc>,
    /// User comment/notes
    pub comment: String,
}

