#include "RustCodeGenerator.h"
#include "Console.h"
#include "Contracts.h"
#include <algorithm>
#include <cctype>
#include <fstream>
#include <functional>
#include <iostream>

namespace bbfm {
RustCodeGenerator::RustCodeGenerator(
    const AST* ast, const SemanticAnalyzer* analyzer, const std::vector<std::string>& namespaces, const std::string& classPrefix) :
    CodeGenerator(ast, analyzer, namespaces, classPrefix)
{
    BuildInheritanceMap();
}

bool RustCodeGenerator::Generate(const std::string& outputPath)
{
    if (nullptr == ast_)
    {
        ReportError("Cannot generate code from null AST");
        return false;
    }

    Console::ReportStatus("Phase 2 (Code Generation) started...");

    // Generate code into output stream
    GenerateFileHeader(outputPath);

    // Generate all declarations
    const auto& declarations = ast_->GetDeclarations();
    for (const auto& decl : declarations)
    {
        if (Declaration::Kind::ENUM == decl->GetKind())
        {
            GenerateEnum(decl->AsEnum());
        }
        else if (Declaration::Kind::CLASS == decl->GetKind())
        {
            GenerateClass(decl->AsClass());
        }
    }

    GenerateFileFooter();

    // Write to file
    std::ofstream outFile(outputPath);
    if (outFile.is_open() == false)
    {
        ReportError("Failed to open output file: " + outputPath);
        return false;
    }

    outFile << output_.str();
    outFile.close();

    Console::ReportStatus("Rust code generated successfully: " + outputPath);
    return HasErrors() == false;
}

std::string RustCodeGenerator::GetFileExtension() const
{
    return ".rs";
}

std::string RustCodeGenerator::GetLanguageName() const
{
    return "Rust";
}

std::string RustCodeGenerator::MapPrimitiveType(PrimitiveType type) const
{
    switch (type)
    {
        case PrimitiveType::STRING:
            return "String";
        case PrimitiveType::INT:
            return "i64";
        case PrimitiveType::REAL:
            return "f64";
        case PrimitiveType::BOOL:
            return "bool";
        case PrimitiveType::TIMESTAMP:
            return "chrono::DateTime<chrono::Utc>";
        case PrimitiveType::TIMESPAN:
            return "chrono::Duration";
        case PrimitiveType::DATE:
            return "chrono::NaiveDate";
        case PrimitiveType::GUID:
            return "uuid::Uuid";
        default:
            return "Unknown";
    }
}

std::string RustCodeGenerator::MapType(const TypeSpec* typeSpec, const CardinalityModifier* cardinality) const
{
    RequireReturn(nullptr != typeSpec, std::string{"()"});

    std::string baseType;

    if (typeSpec->IsPrimitive())
    {
        const PrimitiveTypeSpec* primType = dynamic_cast<const PrimitiveTypeSpec*>(typeSpec);
        baseType                          = MapPrimitiveType(primType->GetType());
    }
    else
    {
        const UserDefinedTypeSpec* userType = dynamic_cast<const UserDefinedTypeSpec*>(typeSpec);
        baseType                            = ApplyClassPrefix(userType->GetTypeName());
    }

    // Handle optional
    if (nullptr != cardinality && cardinality->IsOptional())
    {
        baseType = "Option<" + baseType + ">";
    }

    // Handle arrays
    if (nullptr != cardinality && cardinality->IsArray())
    {
        baseType = "Vec<" + baseType + ">";
    }

    return baseType;
}

void RustCodeGenerator::GenerateFileHeader(const std::string& filename)
{
    // Extract just the filename from path
    const size_t      lastSlash    = filename.find_last_of("/\\");
    const std::string justFilename = (lastSlash != std::string::npos) ? filename.substr(lastSlash + 1) : filename;

    output_ << "// Generated by BBFM Model Compiler\n";
    output_ << "// Target: Rust 2024\n";
    output_ << "// Output: " << justFilename << "\n";
    output_ << "\n";

    // Generate use statements
    output_ << "#![allow(dead_code)]\n";
    output_ << "\n";
    output_ << "use chrono::{DateTime, Duration, NaiveDate, Utc};\n";
    output_ << "use serde::{Deserialize, Serialize};\n";
    output_ << "use uuid::Uuid;\n";
    output_ << "\n";

    // Generate ValidationError enum
    output_ << "/// Validation error for invariant violations\n";
    output_ << "#[derive(Debug, Clone, PartialEq, Eq)]\n";
    output_ << "pub enum ValidationError {\n";
    output_ << "    /// Invariant constraint was violated\n";
    output_ << "    InvariantViolation(&'static str),\n";
    output_ << "    /// Attempted to access/modify field on wrong enum variant\n";
    output_ << "    WrongVariant,\n";
    output_ << "}\n";
    output_ << "\n";

    // Generate FabricMetadata
    output_ << "/// Universal metadata fields present in all BBFM types\n";
    output_ << "#[derive(Debug, Clone, Serialize, Deserialize)]\n";
    output_ << "pub struct FabricMetadata {\n";
    output_ << "    /// Unique identifier for the type itself (same for all instances of a type)\n";
    output_ << "    pub type_id: Uuid,\n";
    output_ << "    /// Unique identifier for this instance\n";
    output_ << "    pub id: Uuid,\n";
    output_ << "    /// Cardinality of the type instance\n";
    output_ << "    pub cardinality: i64,\n";
    output_ << "    /// When this instance was created\n";
    output_ << "    pub creation_date: DateTime<Utc>,\n";
    output_ << "    /// When this instance was last modified\n";
    output_ << "    pub modification_date: DateTime<Utc>,\n";
    output_ << "    /// User comment/notes\n";
    output_ << "    pub comment: String,\n";
    output_ << "}\n";
    output_ << "\n";

    // Open module namespace if specified
    if (namespaces_.empty() == false)
    {
        for (const auto& ns : namespaces_)
        {
            output_ << "pub mod " << ns << " {\n";
            output_ << "    use super::*;\n";
            output_ << "\n";
        }
    }
}

void RustCodeGenerator::GenerateFileFooter()
{
    // Close module namespaces
    if (namespaces_.empty() == false)
    {
        output_ << "\n";
        for (size_t i = 0; i < namespaces_.size(); ++i)
        {
            output_ << "}\n";
        }
    }
}

void RustCodeGenerator::GenerateEnum(const EnumDeclaration* enumDecl)
{
    const std::string enumName = ApplyClassPrefix(enumDecl->GetName());

    WriteIndent(namespaces_.size());
    output_ << "/// Enumeration: " << enumName << "\n";
    WriteIndent(namespaces_.size());
    output_ << "#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\n";
    WriteIndent(namespaces_.size());
    output_ << "pub enum " << enumName << " {\n";

    for (const auto& value : enumDecl->GetValues())
    {
        WriteIndent(namespaces_.size() + 1);
        output_ << value << ",\n";
    }

    WriteIndent(namespaces_.size());
    output_ << "}\n";
    output_ << "\n";
}

void RustCodeGenerator::GenerateClass(const ClassDeclaration* classDecl)
{
    const std::string className = classDecl->GetName();

    // If this class is a base class (has derived classes), generate enum
    if (IsBaseClass(className) == true)
    {
        GenerateInheritedEnum(classDecl);
        return;
    }

    // If this class inherits from another, it will be generated as part of the base enum
    if (classDecl->GetBaseType().empty() == false)
    {
        return; // Skip - handled by base class enum generation
    }

    // Otherwise, generate as struct
    GenerateStruct(classDecl);
    GenerateImpl(classDecl);
}

void RustCodeGenerator::GenerateInheritedEnum(const ClassDeclaration* baseClass)
{
    const std::string baseName = ApplyClassPrefix(baseClass->GetName());

    // Generate base struct for shared fields
    GenerateBaseStruct(baseClass);

    // Generate enum with variants
    WriteIndent(namespaces_.size());
    output_ << "/// Enum for " << baseName << " hierarchy\n";
    WriteIndent(namespaces_.size());
    output_ << "#[derive(Debug, Clone, Serialize, Deserialize)]\n";
    WriteIndent(namespaces_.size());
    output_ << "pub enum " << baseName << " {\n";

    // Generate variant for each derived class
    const auto& derived = derivedClasses_[baseClass->GetName()];
    for (const auto* derivedClass : derived)
    {
        std::string variantName = ApplyClassPrefix(derivedClass->GetName());
        // Remove base name prefix if present (AudioAsset -> Audio if base is Asset)
        if (variantName.length() > baseName.length() && variantName.compare(0, baseName.length(), baseName) == 0)
        {
            variantName = variantName.substr(baseName.length());
        }

        WriteIndent(namespaces_.size() + 1);
        output_ << variantName << " {\n";
        WriteIndent(namespaces_.size() + 2);
        output_ << "base: " << baseName << "Fields,\n";

        // Add derived class fields
        for (const auto& field : derivedClass->GetFields())
        {
            if (field->IsComputed() == true || field->IsAlias() == true)
            {
                continue; // Skip computed and alias fields
            }

            WriteIndent(namespaces_.size() + 2);
            output_ << ToSnakeCase(field->GetName()) << ": " << MapType(field->GetType(), field->GetCardinalityModifier()) << ",\n";
        }

        WriteIndent(namespaces_.size() + 1);
        output_ << "},\n";
    }

    WriteIndent(namespaces_.size());
    output_ << "}\n";
    output_ << "\n";

    // Generate impl block
    GenerateInheritedEnumImpl(baseClass);
}

void RustCodeGenerator::GenerateBaseStruct(const ClassDeclaration* baseClass)
{
    const std::string baseName = ApplyClassPrefix(baseClass->GetName());

    WriteIndent(namespaces_.size());
    output_ << "/// Base fields for " << baseName << "\n";
    WriteIndent(namespaces_.size());
    output_ << "#[derive(Debug, Clone, Serialize, Deserialize)]\n";
    WriteIndent(namespaces_.size());
    output_ << "pub struct " << baseName << "Fields {\n";

    WriteIndent(namespaces_.size() + 1);
    output_ << "pub metadata: FabricMetadata,\n";

    for (const auto& field : baseClass->GetFields())
    {
        if (field->IsComputed() == true || field->IsAlias() == true)
        {
            continue; // Skip computed and alias fields
        }

        WriteIndent(namespaces_.size() + 1);
        output_ << "pub " << ToSnakeCase(field->GetName()) << ": " << MapType(field->GetType(), field->GetCardinalityModifier()) << ",\n";
    }

    WriteIndent(namespaces_.size());
    output_ << "}\n";
    output_ << "\n";
}

void RustCodeGenerator::GenerateStruct(const ClassDeclaration* classDecl)
{
    const std::string className = ApplyClassPrefix(classDecl->GetName());

    WriteIndent(namespaces_.size());
    output_ << "/// Class: " << className << "\n";
    WriteIndent(namespaces_.size());
    output_ << "#[derive(Debug, Clone, Serialize, Deserialize)]\n";
    WriteIndent(namespaces_.size());
    output_ << "pub struct " << className << " {\n";

    // Universal metadata
    WriteIndent(namespaces_.size() + 1);
    output_ << "pub metadata: FabricMetadata,\n";

    // Fields
    for (const auto& field : classDecl->GetFields())
    {
        if (field->IsComputed() == true || field->IsAlias() == true)
        {
            continue; // Skip computed and alias fields (they become methods)
        }

        WriteIndent(namespaces_.size() + 1);
        output_ << "pub " << ToSnakeCase(field->GetName()) << ": " << MapType(field->GetType(), field->GetCardinalityModifier()) << ",\n";
    }

    WriteIndent(namespaces_.size());
    output_ << "}\n";
    output_ << "\n";
}

void RustCodeGenerator::GenerateImpl(const ClassDeclaration* classDecl)
{
    const std::string className = ApplyClassPrefix(classDecl->GetName());

    WriteIndent(namespaces_.size());
    output_ << "impl " << className << " {\n";

    // Generate getters
    for (const auto& field : classDecl->GetFields())
    {
        if (field->IsAlias() == true)
        {
            continue; // Skip aliases for now
        }

        if (field->IsComputed() == true)
        {
            GenerateComputedGetter(field.get(), classDecl, false);
        }
        else
        {
            GenerateGetter(field.get(), className, false);
        }
    }

    // Generate setters for fields with invariants
    for (const auto& field : classDecl->GetFields())
    {
        if (field->IsComputed() == false && field->IsAlias() == false)
        {
            const auto invariants = GetInvariantsForField(field->GetName(), classDecl);
            if (invariants.empty() == false)
            {
                GenerateSetter(field.get(), classDecl, false);
            }
        }
    }

    WriteIndent(namespaces_.size());
    output_ << "}\n";
    output_ << "\n";
}

void RustCodeGenerator::GenerateInheritedEnumImpl(const ClassDeclaration* baseClass)
{
    const std::string baseName = ApplyClassPrefix(baseClass->GetName());
    const auto&       derived  = derivedClasses_[baseClass->GetName()];

    WriteIndent(namespaces_.size());
    output_ << "impl " << baseName << " {\n";

    // Generate getters for base fields
    for (const auto& field : baseClass->GetFields())
    {
        if (field->IsAlias() == true)
        {
            continue;
        }

        if (field->IsComputed() == true)
        {
            GenerateComputedGetter(field.get(), baseClass, true);
        }
        else
        {
            GenerateGetter(field.get(), baseName, true);
        }
    }

    // Generate getters and setters for derived fields
    for (const auto* derivedClass : derived)
    {
        std::string variantName = ApplyClassPrefix(derivedClass->GetName());
        if (variantName.length() > baseName.length() && variantName.compare(0, baseName.length(), baseName) == 0)
        {
            variantName = variantName.substr(baseName.length());
        }

        for (const auto& field : derivedClass->GetFields())
        {
            if (field->IsAlias() == true)
            {
                continue;
            }

            if (field->IsComputed() == true)
            {
                // Computed getter for variant-specific field
                WriteIndent(namespaces_.size() + 1);
                output_ << "/// Get computed field: " << field->GetName() << " (variant: " << variantName << ")\n";
                WriteIndent(namespaces_.size() + 1);
                output_ << "pub fn " << ToSnakeCase(field->GetName()) << "(&self) -> Option<";
                const PrimitiveTypeSpec* primType = dynamic_cast<const PrimitiveTypeSpec*>(field->GetType());
                output_ << MapPrimitiveType(primType->GetType()) << "> {\n";
                WriteIndent(namespaces_.size() + 2);
                output_ << "if let " << baseName << "::" << variantName << " { ";

                // List all fields needed for the expression
                std::vector<std::string> fieldRefs;
                for (const auto& f : derivedClass->GetFields())
                {
                    if (f->IsComputed() == false && f->IsAlias() == false)
                    {
                        fieldRefs.push_back(ToSnakeCase(f->GetName()));
                    }
                }
                for (const auto& f : baseClass->GetFields())
                {
                    if (f->IsComputed() == false && f->IsAlias() == false)
                    {
                        fieldRefs.push_back(ToSnakeCase(f->GetName()));
                    }
                }

                output_ << "base, ";
                for (size_t i = 0; i < fieldRefs.size(); ++i)
                {
                    output_ << fieldRefs[i];
                    if (i < fieldRefs.size() - 1)
                    {
                        output_ << ", ";
                    }
                }
                output_ << ", .. } = self {\n";
                WriteIndent(namespaces_.size() + 3);
                output_ << "Some(" << ExpressionToRust(field->GetInitializer(), "") << ")\n";
                WriteIndent(namespaces_.size() + 2);
                output_ << "} else {\n";
                WriteIndent(namespaces_.size() + 3);
                output_ << "None\n";
                WriteIndent(namespaces_.size() + 2);
                output_ << "}\n";
                WriteIndent(namespaces_.size() + 1);
                output_ << "}\n";
                output_ << "\n";
            }
            else
            {
                // Regular getter
                WriteIndent(namespaces_.size() + 1);
                output_ << "/// Get field: " << field->GetName() << " (variant: " << variantName << ")\n";
                WriteIndent(namespaces_.size() + 1);
                const std::string rustType = MapType(field->GetType(), field->GetCardinalityModifier());
                const bool        needsRef = (rustType.find("String") != std::string::npos || rustType.find("Vec<") != std::string::npos);
                output_ << "pub fn " << ToSnakeCase(field->GetName()) << "(&self) -> Option<";
                if (needsRef == true)
                {
                    output_ << "&" << rustType;
                }
                else
                {
                    output_ << rustType;
                }
                output_ << "> {\n";
                WriteIndent(namespaces_.size() + 2);
                output_ << "if let " << baseName << "::" << variantName << " { " << ToSnakeCase(field->GetName()) << ", .. } = self {\n";
                WriteIndent(namespaces_.size() + 3);
                if (needsRef == true)
                {
                    output_ << "Some(" << ToSnakeCase(field->GetName()) << ")\n";
                }
                else
                {
                    output_ << "Some(*" << ToSnakeCase(field->GetName()) << ")\n";
                }
                WriteIndent(namespaces_.size() + 2);
                output_ << "} else {\n";
                WriteIndent(namespaces_.size() + 3);
                output_ << "None\n";
                WriteIndent(namespaces_.size() + 2);
                output_ << "}\n";
                WriteIndent(namespaces_.size() + 1);
                output_ << "}\n";
                output_ << "\n";
            }

            // Setter if field has invariants
            const auto invariants = GetInvariantsForField(field->GetName(), derivedClass);
            if (invariants.empty() == false && field->IsComputed() == false)
            {
                GenerateSetter(field.get(), derivedClass, true);
            }
        }
    }

    WriteIndent(namespaces_.size());
    output_ << "}\n";
    output_ << "\n";
}

void RustCodeGenerator::GenerateGetter(const Field* field, const std::string& className, bool isInEnum)
{
    Require(nullptr != field);

    const std::string fieldName = ToSnakeCase(field->GetName());
    const std::string rustType  = MapType(field->GetType(), field->GetCardinalityModifier());
    const bool        needsRef  = (rustType.find("String") != std::string::npos || rustType.find("Vec<") != std::string::npos);

    WriteIndent(namespaces_.size() + 1);
    output_ << "/// Get field: " << field->GetName() << "\n";
    WriteIndent(namespaces_.size() + 1);
    output_ << "pub fn " << fieldName << "(&self) -> ";

    if (true == isInEnum)
    {
        if (needsRef == true)
        {
            output_ << "&" << rustType;
        }
        else
        {
            output_ << rustType;
        }
        output_ << " {\n";
        WriteIndent(namespaces_.size() + 2);
        output_ << "match self {\n";

        // Generate match arms for all variants
        const auto& derived = derivedClasses_[className];
        for (size_t i = 0; i < derived.size(); ++i)
        {
            std::string variantName = ApplyClassPrefix(derived[i]->GetName());
            if (variantName.length() > className.length() && variantName.compare(0, className.length(), className) == 0)
            {
                variantName = variantName.substr(className.length());
            }

            WriteIndent(namespaces_.size() + 3);
            output_ << className << "::" << variantName << " { base, .. }";
            if (i < derived.size() - 1)
            {
                output_ << " |\n";
            }
            else
            {
                output_ << " => ";
                if (needsRef == true)
                {
                    output_ << "&base." << fieldName << ",\n";
                }
                else
                {
                    output_ << "base." << fieldName << ",\n";
                }
            }
        }

        WriteIndent(namespaces_.size() + 2);
        output_ << "}\n";
    }
    else
    {
        if (needsRef == true)
        {
            output_ << "&" << rustType << " {\n";
            WriteIndent(namespaces_.size() + 2);
            output_ << "&self." << fieldName << "\n";
        }
        else
        {
            output_ << rustType << " {\n";
            WriteIndent(namespaces_.size() + 2);
            output_ << "self." << fieldName << "\n";
        }
    }

    WriteIndent(namespaces_.size() + 1);
    output_ << "}\n";
    output_ << "\n";
}

void RustCodeGenerator::GenerateSetter(const Field* field, const ClassDeclaration* classDecl, bool isInEnum)
{
    Require(nullptr != field);
    Require(nullptr != classDecl);

    const std::string fieldName  = ToSnakeCase(field->GetName());
    const std::string className  = ApplyClassPrefix(classDecl->GetName());
    const std::string rustType   = MapType(field->GetType(), field->GetCardinalityModifier());
    const auto        invariants = GetInvariantsForField(field->GetName(), classDecl);

    WriteIndent(namespaces_.size() + 1);
    output_ << "/// Set field: " << field->GetName() << " (validates invariants)\n";
    WriteIndent(namespaces_.size() + 1);
    output_ << "pub fn set_" << fieldName << "(&mut self, value: " << rustType << ") -> Result<(), ValidationError> {\n";

    if (true == isInEnum)
    {
        // For enum variants, need to match and update
        const std::string baseName    = classDecl->GetBaseType();
        std::string       variantName = className;
        if (variantName.length() > baseName.length() && variantName.compare(0, baseName.length(), baseName) == 0)
        {
            variantName = variantName.substr(baseName.length());
        }

        WriteIndent(namespaces_.size() + 2);
        output_ << "if let " << ApplyClassPrefix(baseName) << "::" << variantName << " { " << fieldName << ", .. } = self {\n";
        WriteIndent(namespaces_.size() + 3);
        output_ << "let old_value = " << fieldName << ".clone();\n";
        WriteIndent(namespaces_.size() + 3);
        output_ << "*" << fieldName << " = value;\n";

        // Check invariants
        for (const auto* inv : invariants)
        {
            WriteIndent(namespaces_.size() + 3);
            output_ << "if !(" << ExpressionToRust(inv->GetExpression(), "*") << ") {\n";
            WriteIndent(namespaces_.size() + 4);
            output_ << "*" << fieldName << " = old_value;\n";
            WriteIndent(namespaces_.size() + 4);
            output_ << "return Err(ValidationError::InvariantViolation(\"" << inv->GetName() << "\"));\n";
            WriteIndent(namespaces_.size() + 3);
            output_ << "}\n";
        }

        WriteIndent(namespaces_.size() + 3);
        output_ << "Ok(())\n";
        WriteIndent(namespaces_.size() + 2);
        output_ << "} else {\n";
        WriteIndent(namespaces_.size() + 3);
        output_ << "Err(ValidationError::WrongVariant)\n";
        WriteIndent(namespaces_.size() + 2);
        output_ << "}\n";
    }
    else
    {
        WriteIndent(namespaces_.size() + 2);
        output_ << "let old_value = self." << fieldName << ".clone();\n";
        WriteIndent(namespaces_.size() + 2);
        output_ << "self." << fieldName << " = value;\n";

        // Check invariants
        for (const auto* inv : invariants)
        {
            WriteIndent(namespaces_.size() + 2);
            output_ << "if !(";
            output_ << ExpressionToRust(inv->GetExpression()) << ") {\n";
            WriteIndent(namespaces_.size() + 3);
            output_ << "self." << fieldName << " = old_value;\n";
            WriteIndent(namespaces_.size() + 3);
            output_ << "return Err(ValidationError::InvariantViolation(\"" << inv->GetName() << "\"));\n";
            WriteIndent(namespaces_.size() + 2);
            output_ << "}\n";
        }

        WriteIndent(namespaces_.size() + 2);
        output_ << "Ok(())\n";
    }

    WriteIndent(namespaces_.size() + 1);
    output_ << "}\n";
    output_ << "\n";
}

void RustCodeGenerator::GenerateComputedGetter(const Field* field, const ClassDeclaration* classDecl, bool isInEnum)
{
    Require(nullptr != field);
    Require(nullptr != classDecl);

    const std::string        fieldName = ToSnakeCase(field->GetName());
    const PrimitiveTypeSpec* primType  = dynamic_cast<const PrimitiveTypeSpec*>(field->GetType());
    const std::string        rustType  = MapPrimitiveType(primType->GetType());

    WriteIndent(namespaces_.size() + 1);
    output_ << "/// Computed field: " << field->GetName() << "\n";
    WriteIndent(namespaces_.size() + 1);
    output_ << "pub fn " << fieldName << "(&self) -> " << rustType << " {\n";

    if (true == isInEnum)
    {
        WriteIndent(namespaces_.size() + 2);
        output_ << "match self {\n";

        const std::string className = ApplyClassPrefix(classDecl->GetName());
        const auto&       derived   = derivedClasses_[classDecl->GetName()];
        for (size_t i = 0; i < derived.size(); ++i)
        {
            std::string variantName = ApplyClassPrefix(derived[i]->GetName());
            if (variantName.length() > className.length() && variantName.compare(0, className.length(), className) == 0)
            {
                variantName = variantName.substr(className.length());
            }

            WriteIndent(namespaces_.size() + 3);
            output_ << className << "::" << variantName << " { base, .. }";
            if (i < derived.size() - 1)
            {
                output_ << " |\n";
            }
            else
            {
                output_ << " => " << ExpressionToRust(field->GetInitializer(), "base.") << ",\n";
            }
        }

        WriteIndent(namespaces_.size() + 2);
        output_ << "}\n";
    }
    else
    {
        WriteIndent(namespaces_.size() + 2);
        output_ << ExpressionToRust(field->GetInitializer()) << "\n";
    }

    WriteIndent(namespaces_.size() + 1);
    output_ << "}\n";
    output_ << "\n";
}

std::vector<const Invariant*> RustCodeGenerator::GetInvariantsForField(const std::string& fieldName, const ClassDeclaration* classDecl) const
{
    RequireReturn(nullptr != classDecl, std::vector<const Invariant*>{});
    RequireReturn(fieldName.empty() == false, std::vector<const Invariant*>{});

    std::vector<const Invariant*> result;

    for (const auto& inv : classDecl->GetInvariants())
    {
        // Simple check: does the expression reference this field?
        // This is a simplified version - full implementation would traverse the expression tree
        std::function<bool(const Expression*)> referencesField = [&](const Expression* expr) -> bool {
            if (nullptr == expr)
            {
                return false;
            }

            if (const FieldReference* fieldRef = dynamic_cast<const FieldReference*>(expr))
            {
                return fieldRef->GetFieldName() == fieldName;
            }

            if (const BinaryExpression* binExpr = dynamic_cast<const BinaryExpression*>(expr))
            {
                return referencesField(binExpr->GetLeft()) || referencesField(binExpr->GetRight());
            }

            if (const UnaryExpression* unExpr = dynamic_cast<const UnaryExpression*>(expr))
            {
                return referencesField(unExpr->GetOperand());
            }

            return false;
        };

        if (referencesField(inv->GetExpression()) == true)
        {
            result.push_back(inv.get());
        }
    }

    return result;
}

std::string RustCodeGenerator::ExpressionToRust(const Expression* expr, const std::string& prefix) const
{
    if (nullptr == expr)
    {
        return "()";
    }

    // Literal expression
    if (const LiteralExpression* litExpr = dynamic_cast<const LiteralExpression*>(expr))
    {
        const Expression::Type type = litExpr->GetResultType();
        switch (type)
        {
            case Expression::Type::INT:
                return std::to_string(litExpr->GetIntValue());
            case Expression::Type::REAL:
            case Expression::Type::TIMESTAMP:
            case Expression::Type::TIMESPAN:
                return std::to_string(litExpr->GetRealValue());
            case Expression::Type::BOOL:
                return litExpr->GetBoolValue() == true ? "true" : "false";
            case Expression::Type::STRING:
            case Expression::Type::GUID:
                return "\"" + litExpr->GetStringValue() + "\"";
            default:
                return "/* unknown literal */";
        }
    }

    // Field reference
    if (const FieldReference* fieldRef = dynamic_cast<const FieldReference*>(expr))
    {
        return prefix + ToSnakeCase(fieldRef->GetFieldName());
    }

    // Member access
    if (const MemberAccessExpression* memberExpr = dynamic_cast<const MemberAccessExpression*>(expr))
    {
        return ExpressionToRust(memberExpr->GetObject(), prefix) + "." + ToSnakeCase(memberExpr->GetMemberName());
    }

    // Parenthesized expression
    if (const ParenthesizedExpression* parenExpr = dynamic_cast<const ParenthesizedExpression*>(expr))
    {
        return "(" + ExpressionToRust(parenExpr->GetExpression(), prefix) + ")";
    }

    // Binary expression
    if (const BinaryExpression* binExpr = dynamic_cast<const BinaryExpression*>(expr))
    {
        const std::string left  = ExpressionToRust(binExpr->GetLeft(), prefix);
        const std::string right = ExpressionToRust(binExpr->GetRight(), prefix);
        std::string       op;

        switch (binExpr->GetOperator())
        {
            case BinaryExpression::Op::ADD:
                op = " + ";
                break;
            case BinaryExpression::Op::SUB:
                op = " - ";
                break;
            case BinaryExpression::Op::MUL:
                op = " * ";
                break;
            case BinaryExpression::Op::DIV:
                op = " / ";
                break;
            case BinaryExpression::Op::MOD:
                op = " % ";
                break;
            case BinaryExpression::Op::LT:
                op = " < ";
                break;
            case BinaryExpression::Op::GT:
                op = " > ";
                break;
            case BinaryExpression::Op::LE:
                op = " <= ";
                break;
            case BinaryExpression::Op::GE:
                op = " >= ";
                break;
            case BinaryExpression::Op::EQ:
                op = " == ";
                break;
            case BinaryExpression::Op::NE:
                op = " != ";
                break;
            case BinaryExpression::Op::AND:
                op = " && ";
                break;
            case BinaryExpression::Op::OR:
                op = " || ";
                break;
        }

        return "(" + left + op + right + ")";
    }

    // Unary expression
    if (const UnaryExpression* unExpr = dynamic_cast<const UnaryExpression*>(expr))
    {
        const std::string operand = ExpressionToRust(unExpr->GetOperand(), prefix);

        switch (unExpr->GetOperator())
        {
            case UnaryExpression::Op::NEG:
                return "-" + operand;
            case UnaryExpression::Op::NOT:
                return "!" + operand;
        }
    }

    return "/* unknown expression */";
}

std::string RustCodeGenerator::ApplyClassPrefix(const std::string& name) const
{
    if (classPrefix_.empty() == true)
    {
        return name;
    }
    return classPrefix_ + name;
}

std::string RustCodeGenerator::ToSnakeCase(const std::string& name) const
{
    std::string result;
    bool        lastWasUpper = false;

    for (size_t i = 0; i < name.length(); ++i)
    {
        const char c = name[i];

        if (std::isupper(c) != 0)
        {
            if (i > 0 && false == lastWasUpper)
            {
                result += '_';
            }
            result       += std::tolower(c);
            lastWasUpper  = true;
        }
        else
        {
            result       += c;
            lastWasUpper  = false;
        }
    }

    return result;
}

void RustCodeGenerator::BuildInheritanceMap()
{
    // Build map of base class -> derived classes
    for (const auto& decl : ast_->GetDeclarations())
    {
        if (Declaration::Kind::CLASS == decl->GetKind())
        {
            const ClassDeclaration* classDecl = decl->AsClass();
            if (nullptr != classDecl && classDecl->GetBaseType().empty() == false)
            {
                const std::string baseClass = classDecl->GetBaseType();
                derivedClasses_[baseClass].push_back(classDecl);
                baseClasses_.insert(baseClass);
            }
        }
    }
}

bool RustCodeGenerator::IsBaseClass(const std::string& className) const
{
    return baseClasses_.find(className) != baseClasses_.end();
}

void RustCodeGenerator::WriteIndent(int level)
{
    for (int i = 0; i < level; ++i)
    {
        output_ << "    ";
    }
}
} // namespace bbfm
